### ISSUE TITLE
score system

### ISSUE THREAD

**Issue by dev-ale** [alejandro-garcia-fhnw/fhnw-sdent-somethingelse#7]

**Comment by dev-ale** [comment]
Nach jeder Antweot ein Foto, am schluss werden alle Fotos angezeigt.

**Comment by dev-ale** [comment]
Game fertig wenn alle Fragen beantwortet sind.

**Comment by dev-ale** [comment]
evtl. Zeit basiert

**Comment by msladek** [comment]
simple scoring implemented (not time based)
